// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wucizrbtfedhxbzgrjub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Y2l6cmJ0ZmVkaHhiemdyanViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzcwOTksImV4cCI6MjA2NjUxMzA5OX0.Rz_SEoEq_JbBjfed5-uAjJunG0MMe5N769Mi3tbKeno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);